# Generated by Django 5.2 on 2025-05-02 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_emailrecord_order_alter_emailrecord_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailrecord',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.order'),
            preserve_default=False,
        ),
    ]
