# Generated by Django 5.2 on 2025-05-02 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_emailrecord_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailRecord',
        ),
    ]
